/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'analytics-events': AnalyticsEvent;
    experiments: Experiment;
    leads: Lead;
    pages: Page;
    'page-variants': PageVariant;
    'reusable-blocks': ReusableBlock;
    posts: Post;
    media: Media;
    'plugin-collection': PluginCollection;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'analytics-events': AnalyticsEventsSelect<false> | AnalyticsEventsSelect<true>;
    experiments: ExperimentsSelect<false> | ExperimentsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'page-variants': PageVariantsSelect<false> | PageVariantsSelect<true>;
    'reusable-blocks': ReusableBlocksSelect<false> | ReusableBlocksSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'plugin-collection': PluginCollectionSelect<false> | PluginCollectionSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-events".
 */
export interface AnalyticsEvent {
  id: string;
  /**
   * Type of analytics event
   */
  eventType: 'impression' | 'conversion' | 'click' | 'custom';
  /**
   * Which experiment this event belongs to
   */
  experiment?: (string | null) | Experiment;
  /**
   * Which variant was shown
   */
  variant?: (string | null) | PageVariant;
  /**
   * The visitor ID from cookie
   */
  visitorId?: string | null;
  /**
   * Which page the event occurred on
   */
  page?: (string | null) | Page;
  /**
   * The blockId for block-level tracking (matches nanoid(12) from blocks)
   */
  blockId?: string | null;
  /**
   * Custom event name for type="custom" (e.g., "cta_hover", "video_play")
   */
  eventName?: string | null;
  /**
   * Arbitrary metadata for the event
   */
  eventData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * When the event occurred
   */
  timestamp?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiments".
 */
export interface Experiment {
  id: string;
  /**
   * Experiment identifier (e.g., "Holiday Hero Test", "CTA Button Color")
   */
  name: string;
  /**
   * The base page being tested
   */
  page: string | Page;
  /**
   * Page variants to test with traffic allocation
   */
  variants: {
    /**
     * The page variant for this test arm
     */
    variant: string | PageVariant;
    /**
     * Percentage of traffic to send to this variant (0-100)
     */
    trafficPercent: number;
    id?: string | null;
  }[];
  /**
   * Experiment lifecycle state
   */
  status?: ('draft' | 'running' | 'paused' | 'completed') | null;
  /**
   * Block types AI can use for this experiment (empty = all allowed)
   */
  allowedBlockTypes?:
    | (
        | 'accordionBlock'
        | 'contentBlock'
        | 'faqBlock'
        | 'footerBlock'
        | 'heroBlock'
        | 'reusableBlockRef'
        | 'statsBlock'
      )[]
    | null;
  /**
   * When experiment activates (optional, null = manual activation)
   */
  startDate?: string | null;
  /**
   * When experiment ends (optional, null = no auto-end)
   */
  endDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  hero?:
    | {
        headline: string;
        subheadline?: string | null;
        cta?: {
          ctaText?: string | null;
          ctaLink?: string | null;
        };
        media?: (string | null) | Media;
        /**
         * Settings for analytics and variant targeting. Block ID is auto-generated on creation.
         */
        settings?: {
          /**
           * Auto-generated stable identifier. Do not modify unless necessary.
           */
          blockId?: string | null;
          /**
           * Human-readable label for analytics dashboards (e.g., "Homepage Hero", "Pricing FAQ").
           */
          analyticsLabel?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroBlock';
      }[]
    | null;
  content?:
    | (
        | {
            body?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Settings for analytics and variant targeting. Block ID is auto-generated on creation.
             */
            settings?: {
              /**
               * Auto-generated stable identifier. Do not modify unless necessary.
               */
              blockId?: string | null;
              /**
               * Human-readable label for analytics dashboards (e.g., "Homepage Hero", "Pricing FAQ").
               */
              analyticsLabel?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentBlock';
          }
        | {
            items?:
              | {
                  title: string;
                  content?: {
                    root: {
                      type: string;
                      children: {
                        type: string;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Settings for analytics and variant targeting. Block ID is auto-generated on creation.
             */
            settings?: {
              /**
               * Auto-generated stable identifier. Do not modify unless necessary.
               */
              blockId?: string | null;
              /**
               * Human-readable label for analytics dashboards (e.g., "Homepage Hero", "Pricing FAQ").
               */
              analyticsLabel?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'accordionBlock';
          }
        | {
            block: string | ReusableBlock;
            /**
             * Settings for analytics and variant targeting. Block ID is auto-generated on creation.
             */
            settings?: {
              /**
               * Auto-generated stable identifier. Do not modify unless necessary.
               */
              blockId?: string | null;
              /**
               * Human-readable label for analytics dashboards (e.g., "Homepage Hero", "Pricing FAQ").
               */
              analyticsLabel?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'reusableBlockRef';
          }
        | {
            items?:
              | {
                  question: string;
                  answer?: {
                    root: {
                      type: string;
                      children: {
                        type: string;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Settings for analytics and variant targeting. Block ID is auto-generated on creation.
             */
            settings?: {
              /**
               * Auto-generated stable identifier. Do not modify unless necessary.
               */
              blockId?: string | null;
              /**
               * Human-readable label for analytics dashboards (e.g., "Homepage Hero", "Pricing FAQ").
               */
              analyticsLabel?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | {
            items?:
              | {
                  value: string;
                  label: string;
                  icon?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Settings for analytics and variant targeting. Block ID is auto-generated on creation.
             */
            settings?: {
              /**
               * Auto-generated stable identifier. Do not modify unless necessary.
               */
              blockId?: string | null;
              /**
               * Human-readable label for analytics dashboards (e.g., "Homepage Hero", "Pricing FAQ").
               */
              analyticsLabel?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'statsBlock';
          }
      )[]
    | null;
  footer?:
    | {
        text?: string | null;
        /**
         * Settings for analytics and variant targeting. Block ID is auto-generated on creation.
         */
        settings?: {
          /**
           * Auto-generated stable identifier. Do not modify unless necessary.
           */
          blockId?: string | null;
          /**
           * Human-readable label for analytics dashboards (e.g., "Homepage Hero", "Pricing FAQ").
           */
          analyticsLabel?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'footerBlock';
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reusable-blocks".
 */
export interface ReusableBlock {
  id: string;
  title: string;
  blockType: 'accordion' | 'content' | 'faq' | 'footer' | 'stats';
  block?:
    | (
        | {
            items?:
              | {
                  title: string;
                  content?: {
                    root: {
                      type: string;
                      children: {
                        type: string;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Settings for analytics and variant targeting. Block ID is auto-generated on creation.
             */
            settings?: {
              /**
               * Auto-generated stable identifier. Do not modify unless necessary.
               */
              blockId?: string | null;
              /**
               * Human-readable label for analytics dashboards (e.g., "Homepage Hero", "Pricing FAQ").
               */
              analyticsLabel?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'accordionBlock';
          }
        | {
            body?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Settings for analytics and variant targeting. Block ID is auto-generated on creation.
             */
            settings?: {
              /**
               * Auto-generated stable identifier. Do not modify unless necessary.
               */
              blockId?: string | null;
              /**
               * Human-readable label for analytics dashboards (e.g., "Homepage Hero", "Pricing FAQ").
               */
              analyticsLabel?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentBlock';
          }
        | {
            text?: string | null;
            /**
             * Settings for analytics and variant targeting. Block ID is auto-generated on creation.
             */
            settings?: {
              /**
               * Auto-generated stable identifier. Do not modify unless necessary.
               */
              blockId?: string | null;
              /**
               * Human-readable label for analytics dashboards (e.g., "Homepage Hero", "Pricing FAQ").
               */
              analyticsLabel?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'footerBlock';
          }
        | {
            items?:
              | {
                  question: string;
                  answer?: {
                    root: {
                      type: string;
                      children: {
                        type: string;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Settings for analytics and variant targeting. Block ID is auto-generated on creation.
             */
            settings?: {
              /**
               * Auto-generated stable identifier. Do not modify unless necessary.
               */
              blockId?: string | null;
              /**
               * Human-readable label for analytics dashboards (e.g., "Homepage Hero", "Pricing FAQ").
               */
              analyticsLabel?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | {
            items?:
              | {
                  value: string;
                  label: string;
                  icon?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Settings for analytics and variant targeting. Block ID is auto-generated on creation.
             */
            settings?: {
              /**
               * Auto-generated stable identifier. Do not modify unless necessary.
               */
              blockId?: string | null;
              /**
               * Human-readable label for analytics dashboards (e.g., "Homepage Hero", "Pricing FAQ").
               */
              analyticsLabel?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'statsBlock';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-variants".
 */
export interface PageVariant {
  id: string;
  /**
   * Variant identifier (e.g., "Holiday Sale", "Mobile Optimized")
   */
  name: string;
  /**
   * The base page this variant applies to
   */
  page: string | Page;
  /**
   * Lifecycle state of this variant
   */
  status?: ('draft' | 'active' | 'archived') | null;
  /**
   * Replaces hero section when set
   */
  heroOverride?:
    | {
        headline: string;
        subheadline?: string | null;
        cta?: {
          ctaText?: string | null;
          ctaLink?: string | null;
        };
        media?: (string | null) | Media;
        /**
         * Settings for analytics and variant targeting. Block ID is auto-generated on creation.
         */
        settings?: {
          /**
           * Auto-generated stable identifier. Do not modify unless necessary.
           */
          blockId?: string | null;
          /**
           * Human-readable label for analytics dashboards (e.g., "Homepage Hero", "Pricing FAQ").
           */
          analyticsLabel?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroBlock';
      }[]
    | null;
  /**
   * Replaces content section when set
   */
  contentOverride?:
    | (
        | {
            body?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Settings for analytics and variant targeting. Block ID is auto-generated on creation.
             */
            settings?: {
              /**
               * Auto-generated stable identifier. Do not modify unless necessary.
               */
              blockId?: string | null;
              /**
               * Human-readable label for analytics dashboards (e.g., "Homepage Hero", "Pricing FAQ").
               */
              analyticsLabel?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentBlock';
          }
        | {
            items?:
              | {
                  title: string;
                  content?: {
                    root: {
                      type: string;
                      children: {
                        type: string;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Settings for analytics and variant targeting. Block ID is auto-generated on creation.
             */
            settings?: {
              /**
               * Auto-generated stable identifier. Do not modify unless necessary.
               */
              blockId?: string | null;
              /**
               * Human-readable label for analytics dashboards (e.g., "Homepage Hero", "Pricing FAQ").
               */
              analyticsLabel?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'accordionBlock';
          }
        | {
            block: string | ReusableBlock;
            /**
             * Settings for analytics and variant targeting. Block ID is auto-generated on creation.
             */
            settings?: {
              /**
               * Auto-generated stable identifier. Do not modify unless necessary.
               */
              blockId?: string | null;
              /**
               * Human-readable label for analytics dashboards (e.g., "Homepage Hero", "Pricing FAQ").
               */
              analyticsLabel?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'reusableBlockRef';
          }
        | {
            items?:
              | {
                  question: string;
                  answer?: {
                    root: {
                      type: string;
                      children: {
                        type: string;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Settings for analytics and variant targeting. Block ID is auto-generated on creation.
             */
            settings?: {
              /**
               * Auto-generated stable identifier. Do not modify unless necessary.
               */
              blockId?: string | null;
              /**
               * Human-readable label for analytics dashboards (e.g., "Homepage Hero", "Pricing FAQ").
               */
              analyticsLabel?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | {
            items?:
              | {
                  value: string;
                  label: string;
                  icon?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Settings for analytics and variant targeting. Block ID is auto-generated on creation.
             */
            settings?: {
              /**
               * Auto-generated stable identifier. Do not modify unless necessary.
               */
              blockId?: string | null;
              /**
               * Human-readable label for analytics dashboards (e.g., "Homepage Hero", "Pricing FAQ").
               */
              analyticsLabel?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'statsBlock';
          }
      )[]
    | null;
  /**
   * Replaces footer section when set
   */
  footerOverride?:
    | {
        text?: string | null;
        /**
         * Settings for analytics and variant targeting. Block ID is auto-generated on creation.
         */
        settings?: {
          /**
           * Auto-generated stable identifier. Do not modify unless necessary.
           */
          blockId?: string | null;
          /**
           * Human-readable label for analytics dashboards (e.g., "Homepage Hero", "Pricing FAQ").
           */
          analyticsLabel?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'footerBlock';
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: string;
  email: string;
  name?: string | null;
  /**
   * Which experiment this lead was captured from
   */
  experiment?: (string | null) | Experiment;
  /**
   * Which variant the visitor saw
   */
  variant?: (string | null) | PageVariant;
  /**
   * The visitor ID from cookie at time of submission
   */
  visitorId?: string | null;
  /**
   * Which page the form was on
   */
  page?: (string | null) | Page;
  /**
   * Arbitrary additional form fields as JSON object
   */
  formData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Where the lead came from (e.g., "hero-cta", "footer-form")
   */
  source?: string | null;
  /**
   * When this lead converted
   */
  convertedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  addedByPlugin?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-collection".
 */
export interface PluginCollection {
  id: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'analytics-events';
        value: string | AnalyticsEvent;
      } | null)
    | ({
        relationTo: 'experiments';
        value: string | Experiment;
      } | null)
    | ({
        relationTo: 'leads';
        value: string | Lead;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'page-variants';
        value: string | PageVariant;
      } | null)
    | ({
        relationTo: 'reusable-blocks';
        value: string | ReusableBlock;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'plugin-collection';
        value: string | PluginCollection;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-events_select".
 */
export interface AnalyticsEventsSelect<T extends boolean = true> {
  eventType?: T;
  experiment?: T;
  variant?: T;
  visitorId?: T;
  page?: T;
  blockId?: T;
  eventName?: T;
  eventData?: T;
  timestamp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiments_select".
 */
export interface ExperimentsSelect<T extends boolean = true> {
  name?: T;
  page?: T;
  variants?:
    | T
    | {
        variant?: T;
        trafficPercent?: T;
        id?: T;
      };
  status?: T;
  allowedBlockTypes?: T;
  startDate?: T;
  endDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  experiment?: T;
  variant?: T;
  visitorId?: T;
  page?: T;
  formData?: T;
  source?: T;
  convertedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hero?:
    | T
    | {
        heroBlock?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              cta?:
                | T
                | {
                    ctaText?: T;
                    ctaLink?: T;
                  };
              media?: T;
              settings?:
                | T
                | {
                    blockId?: T;
                    analyticsLabel?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  content?:
    | T
    | {
        contentBlock?:
          | T
          | {
              body?: T;
              settings?:
                | T
                | {
                    blockId?: T;
                    analyticsLabel?: T;
                  };
              id?: T;
              blockName?: T;
            };
        accordionBlock?:
          | T
          | {
              items?:
                | T
                | {
                    title?: T;
                    content?: T;
                    id?: T;
                  };
              settings?:
                | T
                | {
                    blockId?: T;
                    analyticsLabel?: T;
                  };
              id?: T;
              blockName?: T;
            };
        reusableBlockRef?:
          | T
          | {
              block?: T;
              settings?:
                | T
                | {
                    blockId?: T;
                    analyticsLabel?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              settings?:
                | T
                | {
                    blockId?: T;
                    analyticsLabel?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statsBlock?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    icon?: T;
                    id?: T;
                  };
              settings?:
                | T
                | {
                    blockId?: T;
                    analyticsLabel?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  footer?:
    | T
    | {
        footerBlock?:
          | T
          | {
              text?: T;
              settings?:
                | T
                | {
                    blockId?: T;
                    analyticsLabel?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-variants_select".
 */
export interface PageVariantsSelect<T extends boolean = true> {
  name?: T;
  page?: T;
  status?: T;
  heroOverride?:
    | T
    | {
        heroBlock?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              cta?:
                | T
                | {
                    ctaText?: T;
                    ctaLink?: T;
                  };
              media?: T;
              settings?:
                | T
                | {
                    blockId?: T;
                    analyticsLabel?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  contentOverride?:
    | T
    | {
        contentBlock?:
          | T
          | {
              body?: T;
              settings?:
                | T
                | {
                    blockId?: T;
                    analyticsLabel?: T;
                  };
              id?: T;
              blockName?: T;
            };
        accordionBlock?:
          | T
          | {
              items?:
                | T
                | {
                    title?: T;
                    content?: T;
                    id?: T;
                  };
              settings?:
                | T
                | {
                    blockId?: T;
                    analyticsLabel?: T;
                  };
              id?: T;
              blockName?: T;
            };
        reusableBlockRef?:
          | T
          | {
              block?: T;
              settings?:
                | T
                | {
                    blockId?: T;
                    analyticsLabel?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              settings?:
                | T
                | {
                    blockId?: T;
                    analyticsLabel?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statsBlock?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    icon?: T;
                    id?: T;
                  };
              settings?:
                | T
                | {
                    blockId?: T;
                    analyticsLabel?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  footerOverride?:
    | T
    | {
        footerBlock?:
          | T
          | {
              text?: T;
              settings?:
                | T
                | {
                    blockId?: T;
                    analyticsLabel?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reusable-blocks_select".
 */
export interface ReusableBlocksSelect<T extends boolean = true> {
  title?: T;
  blockType?: T;
  block?:
    | T
    | {
        accordionBlock?:
          | T
          | {
              items?:
                | T
                | {
                    title?: T;
                    content?: T;
                    id?: T;
                  };
              settings?:
                | T
                | {
                    blockId?: T;
                    analyticsLabel?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contentBlock?:
          | T
          | {
              body?: T;
              settings?:
                | T
                | {
                    blockId?: T;
                    analyticsLabel?: T;
                  };
              id?: T;
              blockName?: T;
            };
        footerBlock?:
          | T
          | {
              text?: T;
              settings?:
                | T
                | {
                    blockId?: T;
                    analyticsLabel?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              settings?:
                | T
                | {
                    blockId?: T;
                    analyticsLabel?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statsBlock?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    icon?: T;
                    id?: T;
                  };
              settings?:
                | T
                | {
                    blockId?: T;
                    analyticsLabel?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  addedByPlugin?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plugin-collection_select".
 */
export interface PluginCollectionSelect<T extends boolean = true> {
  id?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}